import { readFileSync } from 'node:fs';

/**
 * Spec-Example Tests — Format Branded Types in Generated Contracts
 *
 * Covers:
 * - Branded type definitions for formatted schemas (date-time, uuid, int32, double, email, custom)
 * - Exclusion of binary/byte formats from branding
 * - Exclusion of empty format strings from branding
 * - Nullable branded types render as union with null
 * - Enum wins over format (no branded type for enum+format)
 * - Branded types used in array items, object properties, additionalProperties
 * - Branded type definitions appear before schema types
 * - Branded types are deduplicated
 */
import { describe, expect, it } from 'vitest';

import { generateContracts } from '../../src/generator/contracts-generator.js';
import { RefResolver } from '../../src/parser/ref-resolver.js';
import type { OpenAPIDocument } from '../../src/types/openapi.js';

function loadFormatBrandsSpec(): { doc: OpenAPIDocument; resolver: RefResolver } {
  const raw = readFileSync(new URL('../fixtures/format-brands.json', import.meta.url), 'utf-8');
  const doc = JSON.parse(raw) as OpenAPIDocument;
  const resolver = new RefResolver(doc);
  return { doc, resolver };
}

describe('Format branding in generated contracts', () => {
  const { doc, resolver } = loadFormatBrandsSpec();
  const result = generateContracts(doc, resolver);

  it('emits branded type definitions for formatted schemas', () => {
    expect(result).toMatchSnapshot();
  });

  it('does NOT emit branded types for binary/byte formats', () => {
    expect(result).not.toContain('BinaryString');
    expect(result).not.toContain('ByteString');
  });

  it('does NOT emit branded type for empty format', () => {
    expect(result).not.toContain("String & { readonly __format?: ''");
  });

  it('nullable branded type renders as union with null', () => {
    expect(result).toMatchSnapshot();
  });

  it('enum wins over format — no branded type for enum+format', () => {
    expect(result).toMatchSnapshot();
  });

  it('array items with format use branded type', () => {
    expect(result).toMatchSnapshot();
  });

  it('object properties with format use branded type', () => {
    expect(result).toMatchSnapshot();
  });

  it('additionalProperties with format use branded type', () => {
    expect(result).toMatchSnapshot();
  });

  it('branded type definitions appear before schema types', () => {
    const headerIdx = result.indexOf('// Auto-generated by genoc');
    const brandedIdx = result.indexOf(
      "export type DateTimeString = string & { readonly __format?: 'date-time' };"
    );
    const schemaIdx = result.indexOf('export type DateString =');

    expect(headerIdx).toBeGreaterThan(-1);
    expect(brandedIdx).toBeGreaterThan(-1);
    expect(schemaIdx).toBeGreaterThan(-1);
    expect(headerIdx).toBeLessThan(brandedIdx);
    expect(brandedIdx).toBeLessThan(schemaIdx);
  });

  it('branded types are deduplicated', () => {
    const count = result.split('export type DateTimeString =').length - 1;
    expect(count).toBe(1);
  });
});
