import { execSync } from 'child_process';
import { readFileSync, writeFileSync, rmSync } from 'fs';
import { mkdtemp } from 'fs/promises';
import { tmpdir } from 'os';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

import { describe, it, expect, beforeAll, afterAll } from 'vitest';

import { generateClient, generateFullOutput } from '../../src/generator/client-generator.js';
import { generateContracts } from '../../src/generator/contracts-generator.js';
import { RefResolver } from '../../src/parser/ref-resolver.js';
import { loadFromFile } from '../../src/parser/spec-reader.js';
import type { GeneratorConfig } from '../../src/types/client.js';
import type { OpenAPIDocument } from '../../src/types/openapi.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIXTURE_PATH = join(__dirname, '../fixtures/openapi-3.0-full.yaml');
const PROJECT_ROOT = join(__dirname, '../../');

const TSC = join(PROJECT_ROOT, 'node_modules/.bin/tsc');
const TSC_FLAGS = [
  '--strict',
  '--noEmit',
  '--esModuleInterop',
  '--module',
  'NodeNext',
  '--moduleResolution',
  'NodeNext',
  '--target',
  'ES2022',
  '--skipLibCheck',
].join(' ');

describe('OpenAPI 3.0 Mega-Spec Integration Test', () => {
  let doc: OpenAPIDocument;
  let contracts: string;
  let client: string;
  let tmpDir: string;

  beforeAll(async () => {
    doc = await loadFromFile(FIXTURE_PATH);
    const config: GeneratorConfig = {
      input: FIXTURE_PATH,
      outputDir: '/tmp/mega-spec-3.0-test',
    };
    const result = generateClient(doc, config);
    contracts = result.contracts;
    client = result.client;
  });

  it('loads mega-spec.yaml and produces contracts and client strings', async () => {
    expect(doc).toBeDefined();
    expect(doc.openapi).toBe('3.0.0');
    expect(doc.info.title).toBe('OpenAPI 3.0 Mega Spec');
    expect(doc.info.version).toBe('1.0.0');

    expect(typeof contracts).toBe('string');
    expect(typeof client).toBe('string');
    expect(contracts.length).toBeGreaterThan(0);
    expect(client.length).toBeGreaterThan(0);

    expect(contracts).toContain('// Auto-generated by genoc from OpenAPI 3.0.0 spec. DO NOT EDIT.');
    expect(client).toContain('// Auto-generated by genoc from OpenAPI 3.0.0 spec. DO NOT EDIT.');
  });

  it('generated contracts compile with tsc --strict --noEmit', async () => {
    tmpDir = await mkdtemp(join(tmpdir(), 'mega-spec-3.0-contracts-'));
    const contractsFile = join(tmpDir, 'contracts.ts');
    writeFileSync(contractsFile, contracts, 'utf-8');

    const result = execSync(`${TSC} ${TSC_FLAGS} ${contractsFile}`, {
      cwd: tmpDir,
      encoding: 'utf-8',
      timeout: 60000,
    }).trim();

    expect(result).toBe('');
  });

  it('generated client compiles with tsc --strict --noEmit', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'mega-spec-3.0-client-'));
    writeFileSync(join(dir, 'contracts.ts'), contracts, 'utf-8');
    writeFileSync(join(dir, 'client.ts'), client, 'utf-8');

    const result = execSync(`${TSC} ${TSC_FLAGS} client.ts`, {
      cwd: dir,
      encoding: 'utf-8',
      timeout: 60000,
    }).trim();

    expect(result).toBe('');
  });

  it('generates server parameter types', () => {
    expect(contracts).toContain('export interface Server1Params');
    expect(contracts).toContain('@default development');
    expect(contracts).toContain('/** Server: https://{env}.api.example.com/{basePath} */');

    expect(contracts).toContain('export interface Server2Params');
    expect(contracts).toContain('@default us');
    expect(contracts).toContain('/** Server: https://backup.api.example.com/v2 */');
  });

  it('generates security scheme types', () => {
    expect(contracts).toContain('export type ApiKeyQueryAuth');
    expect(contracts).toContain('type: "apiKey"');
    expect(contracts).toContain('in: "query"');
    expect(contracts).toContain('name: "api_key"');

    expect(contracts).toContain('export type ApiKeyHeaderAuth');
    expect(contracts).toContain('in: "header"');
    expect(contracts).toContain('name: "X-API-Key"');

    expect(contracts).toContain('OAuth2ImplicitAuth');
    expect(contracts).toContain('implicit:');
    expect(contracts).toContain('authorizationUrl:');

    expect(contracts).toContain('SecuritySchemes =');
  });

  it('generates data type exports', () => {
    expect(contracts).toContain('export type StringType = string');
    expect(contracts).toContain('export type NumberType = number');
    expect(contracts).toContain('export type IntegerType = number');
    expect(contracts).toContain('export type BooleanType = boolean');
    expect(contracts).toContain('export type ArrayType = string[]');
    expect(contracts).toContain('export type ObjectType =');
    expect(contracts).toContain('name: string');
    expect(contracts).toContain('value?: number');
  });

  it('handles nullable keyword (3.0-specific)', () => {
    expect(contracts).toContain('export type NullableString = string | null');
    expect(contracts).toContain('export type NullableObject =');
    expect(contracts).toContain('} | null');
    expect(contracts).toContain("NullableEnum = 'active' | 'inactive' | 'pending' | null");
    expect(contracts).toContain('export type NullableArray = string[] | null');
    expect(contracts).toContain('export type NullableAllOf =');
  });

  it('generates schema composition types', () => {
    expect(contracts).toContain('export type AllOfSchema = string & number');
    expect(contracts).toContain('export type OneOfSchema = string | number');
    expect(contracts).toContain('export type AnyOfSchema = string | number');
    expect(contracts).toContain('export type DiscriminatorSchema =');
  });

  it('generates enum and const types', () => {
    expect(contracts).toContain("EnumSchema = 'option1' | 'option2' | 'option3'");
    expect(contracts).toContain('export type ConstSchema =');
  });

  it('generates types with default values', () => {
    expect(contracts).toContain('export type DefaultSchema =');
    expect(contracts).toContain('name?: string');
    expect(contracts).toContain('count?: number');
  });

  it('generates readOnly and writeOnly types', () => {
    expect(contracts).toContain('export type ReadOnlySchema =');
    expect(contracts).toContain('readonly_field: string');
    expect(contracts).toContain('normal_field: string');

    expect(contracts).toContain('export type WriteOnlySchema =');
    expect(contracts).toContain('writeonly_field: string');
    expect(contracts).toContain('normal_field: string');
  });

  it('generates format-branded types', () => {
    expect(contracts).toContain('export type FormatSchema =');
    expect(contracts).toContain('DateTimeString');
    expect(contracts).toContain('UuidString');
  });

  it('generates additional properties types', () => {
    expect(contracts).toContain('export type AdditionalPropertiesSchema =');
    expect(contracts).toContain('known_prop');
    expect(contracts).toContain('[key: string]: number');
  });

  it('generates required field types', () => {
    expect(contracts).toContain('export type RequiredSchema =');
    expect(contracts).toContain('required_field: string');
    expect(contracts).toContain('optional_field?: string');
  });

  it('generates file upload types', () => {
    expect(contracts).toContain('export type FileUpload =');
    expect(contracts).toContain('file:');
    expect(contracts).toContain('text_file:');
    expect(contracts).toContain('regular_file');
  });

  it('generates nested schemas and references', () => {
    expect(contracts).toContain('export type NestedSchema =');
    expect(contracts).toContain('data: ObjectType');
    expect(contracts).toContain('tags?: string[]');
    expect(contracts).toContain('config?: DefaultSchema & { extra: string; }');
    expect(contracts).toContain('files?: FileUpload[]');
  });

  it('handles circular references without infinite recursion', () => {
    expect(contracts).toContain('export type CircularA =');
    expect(contracts).toContain('reference?: CircularB');
    expect(contracts).toContain('export type CircularB =');
    expect(contracts).toContain('reference?: CircularA');
  });

  it('strips $ref siblings (3.0-specific behavior)', () => {
    expect(contracts).toContain('export type RefTarget = string');
    expect(contracts).toContain('Original target description');
    expect(contracts).toContain('export type RefWithSibling =');
    expect(contracts).toContain('RefTarget & { extra_field: string; }');
  });

  it('generates parameter types', () => {
    expect(contracts).toContain(
      'GetQueryQuery = { limit?: number; offset?: number; filter?: string; }'
    );

    expect(contracts).toContain(
      'GetHeadersHeaders = { "X-Custom-Header": string; "X-Trace-ID": string; }'
    );

    expect(contracts).not.toContain('GetCookiesCookie');
  });

  it('generates request body types', () => {
    expect(contracts).toContain('PostJsonBodyBody = { name: string; value?: number; }');
    expect(contracts).toContain('PostFormBodyBody = { field1: string; field2?: number; }');
    expect(contracts).toContain('PostBinaryBodyBody = Blob');
  });

  it('generates response and error types', () => {
    expect(contracts).toContain('GetStringResponse =');
    expect(contracts).toContain('result: string');
    expect(contracts).toContain('GetStringError400 =');
    expect(contracts).toContain('GetStringError500 =');
    expect(contracts).toContain('GetStringErrors =');

    expect(contracts).toContain('GetBinaryResponseResponse = StreamResponse');
    expect(contracts).toContain('GetImageResponseResponse = StreamResponse');
    expect(contracts).toContain('GetEmptyResponseResponse = void');

    expect(contracts).toContain('GetErrorHandlingError401 =');
    expect(contracts).toContain('GetErrorHandlingError403 =');
    expect(contracts).toContain('GetErrorHandlingError404 =');
    expect(contracts).toContain('GetErrorHandlingError500 =');
    expect(contracts).toContain('GetErrorHandlingErrors =');
    expect(contracts).toContain('ApiError<400,');
    expect(contracts).toContain('ApiError<401,');
    expect(contracts).toContain('ApiError<403,');
    expect(contracts).toContain('ApiError<404,');
    expect(contracts).toContain('ApiError<500,');
  });

  it('generates all HTTP methods', () => {
    expect(client).toContain('getAllMethods: decorateWithErrors<');
    expect(client).toContain('postAllMethods: decorateWithErrors<');
    expect(client).toContain('putAllMethods: decorateWithErrors<');
    expect(client).toContain('patchAllMethods: decorateWithErrors<');
    expect(client).toContain('deleteAllMethods: decorateWithErrors<');
    expect(client).toContain('optionsAllMethods: decorateWithErrors<');
    expect(client).toContain('headAllMethods: decorateWithErrors<');
    expect(client).toContain('traceAllMethods: decorateWithErrors<');
  });

  it('uses path-based method naming', () => {
    expect(client).toContain('getString: decorateWithErrors<');
    expect(client).toContain('getNullable: decorateWithErrors<');
    expect(client).toContain('getAllMethods: decorateWithErrors<');
    expect(client).toContain('postAllMethods: decorateWithErrors<');
  });

  it('marks deprecated operations', () => {
    expect(client).toContain('@deprecated');
    expect(client).toContain('getDeprecated: decorateWithErrors<');
  });

  it('includes tags in JSDoc', () => {
    expect(client).toContain('@category data-types');
    expect(client).toContain('@category schema-keywords');
    expect(client).toContain('@category parameters');
  });

  it('handles file uploads in client methods', () => {
    expect(client).toContain('postUpload: decorateWithErrors<');
    expect(client).toContain('formData.append');
    expect(client).toContain('body.file_field.data');
    expect(client).toContain('body.file_field.filename');
  });

  it('handles binary responses', () => {
    expect(client).toContain('getBinaryResponse: decorateWithErrors<');
    expect(client).toContain('expectStream: true');
    expect(client).toContain('getImageResponse: decorateWithErrors<');
  });

  it('has security scheme types but no auth enforcement', () => {
    expect(contracts).toContain('SecuritySchemes =');
    expect(client).not.toContain('ApiKeyQueryAuth');
    expect(client).not.toContain('Authorization');
  });

  it("Tier 2 features don't crash", () => {
    expect(contracts).toContain('GetTier2ParamsQuery = { style_test?: string');
    expect(contracts).toContain('GetTier2ValidationQuery = { min_items?: string[]');

    expect(client).toContain('getTier2Params: decorateWithErrors<');
    expect(client).toContain('getTier2Validation: decorateWithErrors<');
  });

  it('handles exclusiveMinimum/exclusiveMaximum as booleans (3.0-specific)', () => {
    expect(contracts).toContain('GetExclusiveMinMaxQuery = {');
    expect(contracts).toContain('exclusive_min?: number');
    expect(contracts).toContain('exclusive_max?: number');
  });

  it('handles nullable keyword in response schemas', () => {
    expect(contracts).toContain('GetNullableTestResponse = string | null');
  });

  it('handles nullable keyword in request body schemas', () => {
    expect(contracts).toContain('PostNullableObjectTestBody = NullableObject');
  });

  it('handles chained $ref resolution', () => {
    expect(contracts).toContain('export type LevelA = LevelB;');
    expect(contracts).toContain('export type LevelB = LevelC;');
    expect(contracts).toContain('export type LevelC = {');
    expect(contracts).toContain('value: string');
  });

  it('handles complex paths with multiple parameters', () => {
    expect(client).toContain('getUsersByUserIdPostsByPostId: decorateWithErrors<');
    expect(client).toContain('userId: string');
    expect(client).toContain('postId: string');
  });

  it('uses first content type for request bodies', () => {
    expect(contracts).toContain('PostContentNegotiationBody = { json_data: string;');
    expect(contracts).not.toContain('xml_data');
  });

  it('handles optional request bodies', () => {
    expect(client).toContain('postOptionalBody: decorateWithErrors<');
    expect(contracts).toContain('PostOptionalBodyBody = { optional_data?: string; }');
  });

  it('handles inline schemas in operations', () => {
    expect(contracts).toContain('PostInlineSchemaBody = { inline_field: string;');
    expect(contracts).toContain('deep: number');
    expect(contracts).toContain('PostInlineSchemaResponse = { result_id:');
    expect(contracts).toContain('created_at:');
  });

  it('strips $ref siblings in path operation schemas (3.0-specific)', () => {
    expect(contracts).toContain('ref_with_sibling: DescriptionSchema & { extra_field: string; }');
    expect(contracts).toContain('normal_ref: DescriptionSchema');
  });

  it('generates error classes', () => {
    expect(contracts).toContain(
      'export class ApiError<TStatus extends number, TData> extends Error'
    );
    expect(contracts).toContain('UnspecifiedApiError extends ApiError<number, unknown>');
    expect(contracts).toContain('RequesterFailError extends Error');
  });

  it('generates StreamResponse class', () => {
    expect(contracts).toContain('export class StreamResponse');
  });

  it('generates ErrorResponse class', () => {
    expect(contracts).toContain('export class ErrorResponse');
  });

  it('does not emit validation constraint keywords in type output', () => {
    expect(contracts).not.toContain('minItems:');
    expect(contracts).not.toContain('maxItems:');
    expect(contracts).not.toContain('minLength:');
    expect(contracts).not.toContain('maxLength:');
  });

  it('does not generate webhook-related output', () => {
    expect(client).not.toContain('Webhook');
    expect(client).not.toContain('webhook');
  });

  describe('Full output pipeline', () => {
    let fullTmpDir: string;

    beforeAll(async () => {
      fullTmpDir = await mkdtemp(join(tmpdir(), 'mega-spec-3.0-full-'));
      const doc = await loadFromFile(FIXTURE_PATH);
      const config: GeneratorConfig = {
        input: FIXTURE_PATH,
        outputDir: fullTmpDir,
      };
      await generateFullOutput(doc, config);
    });

    afterAll(() => {
      rmSync(fullTmpDir, { recursive: true, force: true });
    });

    it('writes contracts.ts and client.ts to disk', () => {
      const contractsFile = join(fullTmpDir, 'contracts.ts');
      const clientFile = join(fullTmpDir, 'client.ts');

      const contractsContent = readFileSync(contractsFile, 'utf-8');
      const clientContent = readFileSync(clientFile, 'utf-8');

      expect(contractsContent).toContain('export type StringType = string');
      expect(contractsContent).toContain('export type ApiKeyQueryAuth');
      expect(contractsContent).toContain('export interface Server1Params');
      expect(contractsContent).toContain('NullableString = string | null');

      expect(clientContent).toContain('export function createClient');
      expect(clientContent).toContain("from './contracts.js'");
      expect(clientContent).toContain('getString: decorateWithErrors<');
      expect(clientContent).toContain('postUpload: decorateWithErrors<');
    });
  });
});
