// Feature coverage: 3.1-#95 (openIdConnect), 3.1-#96 (security requirements),
// 3.1-#97 (server URLs), 3.1-#98 (server variables), 3.1-#99 (enum for variables),
// 3.1-#100 (default variable values), 3.1-#101 (multiple servers),
// 3.1-#102 (GET), 3.1-#103 (POST), 3.1-#104 (PUT), 3.1-#105 (PATCH),
// 3.1-#106 (DELETE), 3.1-#107 (OPTIONS), 3.1-#108 (HEAD), 3.1-#109 (TRACE),
// 3.1-#110 (operationId), 3.1-#111 (summary), 3.1-#112 (description),
// 3.1-#113 (tags), 3.1-#114 (deprecated operation)

/**
 * Validation Tests — OpenAPI 3.1 Path Operations, Servers & Security
 *
 * Tests every feature from the "Security Schemes" (3.1-#95-#96), "Servers"
 * (3.1-#97-#101), and "Path Operations" (3.1-#102-#114) sections of the
 * feature enumeration.
 *
 * Tier 1 (most features): generateClient + string matching on TypeScript output
 * Tier 2 (#95, #96): verify no crash + type defs generated but no enforcement code
 */
import { describe, expect, it } from 'vitest';
import { parse as parseYaml } from 'yaml';

import { generateClient as generateClientStrings } from '../../src/generator/client-generator.js';
import { generateContracts } from '../../src/generator/contracts-generator.js';
import { RefResolver } from '../../src/parser/ref-resolver.js';
import type { GeneratorConfig } from '../../src/types/client.js';
import type { OpenAPIDocument } from '../../src/types/openapi.js';

// ── Helpers ────────────────────────────────────────────────────────────────

function generateFromYaml(yaml: string): string {
  const doc = parseYaml(yaml) as OpenAPIDocument;
  const resolver = new RefResolver(doc);
  return generateContracts(doc, resolver);
}

function generateClientFromYaml(
  yaml: string,
  config?: Partial<GeneratorConfig>
): { contracts: string; client: string } {
  const doc = parseYaml(yaml) as OpenAPIDocument;
  const fullConfig: GeneratorConfig = {
    input: 'test.yaml',
    outputDir: '/tmp/test',
    ...config,
  };
  return generateClientStrings(doc, fullConfig);
}

// ── Security Schemes (3.1-#95-#96) ────────────────────────────────────────

describe('OpenAPI 3.1 — Security Schemes (3.1-#95-#96)', () => {
  // 3.1-#95: openIdConnect — Tier 2
  it('3.1-#95: openIdConnect scheme generates type def with openIdConnectUrl', () => {
    const contracts = generateFromYaml(`
      openapi: "3.1.0"
      info: { title: Test, version: "1.0.0" }
      paths: {}
      components:
        securitySchemes:
          oidc:
            type: openIdConnect
            openIdConnectUrl: "https://example.com/.well-known/openid-configuration"
    `);

    // Type def generated with openIdConnect-specific fields
    expect(contracts).toContain('OidcAuth');
    expect(contracts).toContain('type: "openIdConnect"');
    expect(contracts).toContain(
      'openIdConnectUrl: "https://example.com/.well-known/openid-configuration"'
    );
  });

  // 3.1-#96: security requirements — Tier 2
  it('3.1-#96: security requirements on operations do not generate enforcement code', () => {
    const { contracts, client } = generateClientFromYaml(`
      openapi: "3.1.0"
      info: { title: Test, version: "1.0.0" }
      paths:
        /secure:
          get:
            security:
              - bearerAuth: []
            responses:
              "200": { description: OK }
      components:
        securitySchemes:
          bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT
    `);

    // Security scheme type def is generated
    expect(contracts).toContain('BearerAuthAuth');
    // But the client method does NOT include any auth/token enforcement
    expect(client).not.toContain('Authorization');
    expect(client).not.toContain('bearer');
    expect(client).not.toContain('token');
    // Method still works normally — security is just metadata
    expect(client).toContain('getSecure');
  });
});

// ── Servers (3.1-#97-#101) ────────────────────────────────────────────────

describe('OpenAPI 3.1 — Servers (3.1-#97-#101)', () => {
  // 3.1-#97: server URLs — Tier 1
  it('3.1-#97: server URLs produce ServerParams comment in contracts', () => {
    const contracts = generateFromYaml(`
      openapi: "3.1.0"
      info: { title: Test, version: "1.0.0" }
      paths: {}
      servers:
        - url: "https://api.example.com/v1"
    `);

    // No variables → no ServerParams type, but no crash either
    expect(contracts).toContain('Auto-generated by genoc');
  });

  // 3.1-#98: server variables — Tier 1
  it('3.1-#98: server variables generate ServerParams interface', () => {
    const contracts = generateFromYaml(`
      openapi: "3.1.0"
      info: { title: Test, version: "1.0.0" }
      paths: {}
      servers:
        - url: "https://{env}.api.example.com"
          variables:
            env:
              default: production
    `);

    // ServerParams interface generated with the variable
    expect(contracts).toContain('export interface ServerParams {');
    expect(contracts).toContain('env: string;');
    // Server URL comment
    expect(contracts).toContain('Server: https://{env}.api.example.com');
  });

  // 3.1-#99: enum for variables — Tier 1
  it('3.1-#99: server variable enum restricts type to string literal union', () => {
    const contracts = generateFromYaml(`
      openapi: "3.1.0"
      info: { title: Test, version: "1.0.0" }
      paths: {}
      servers:
        - url: "https://{env}.api.example.com"
          variables:
            env:
              default: production
              enum: [production, staging, development]
    `);

    // Enum produces string literal union
    expect(contracts).toContain('"production" | "staging" | "development"');
    expect(contracts).toContain('env:');
  });

  // 3.1-#100: default variable values — Tier 1
  it('3.1-#100: default variable values emitted as @default JSDoc', () => {
    const contracts = generateFromYaml(`
      openapi: "3.1.0"
      info: { title: Test, version: "1.0.0" }
      paths: {}
      servers:
        - url: "https://{env}.api.example.com"
          variables:
            env:
              default: production
              description: The deployment environment
    `);

    // Default value appears in JSDoc
    expect(contracts).toContain('@default production');
    // Description also appears in JSDoc
    expect(contracts).toContain('The deployment environment');
  });

  // 3.1-#101: multiple servers — Tier 1
  it('3.1-#101: multiple servers generate numbered ServerParams interfaces', () => {
    const contracts = generateFromYaml(`
      openapi: "3.1.0"
      info: { title: Test, version: "1.0.0" }
      paths: {}
      servers:
        - url: "https://api.example.com/{version}"
          variables:
            version:
              default: v1
        - url: "https://sandbox.api.example.com/{version}"
          variables:
            version:
              default: v2
    `);

    // Two numbered server param interfaces
    expect(contracts).toContain('export interface Server1Params {');
    expect(contracts).toContain('export interface Server2Params {');
    // Both have the version variable
    expect(contracts).toContain('Server: https://api.example.com/{version}');
    expect(contracts).toContain('Server: https://sandbox.api.example.com/{version}');
  });
});

// ── Path Operations: HTTP Methods (3.1-#102-#109) ─────────────────────────

describe('OpenAPI 3.1 — HTTP Methods (3.1-#102-#109)', () => {
  // 3.1-#102: GET — Tier 1
  it('3.1-#102: GET operation generates client method with GET request', () => {
    const { contracts, client } = generateClientFromYaml(`
      openapi: "3.1.0"
      info: { title: Test, version: "1.0.0" }
      paths:
        /items:
          get:
            responses:
              "200":
                description: List
                content:
                  application/json:
                    schema:
                      type: array
                      items:
                        type: string
    `);

    // Contracts: response type
    expect(contracts).toContain('export type GetItemsResponse = string[];');
    // Client: method named correctly
    expect(client).toContain('getItems:');
    // Client: uses GET method
    expect(client).toContain('"GET"');
    // Client: requester called correctly
    expect(client).toContain('requester<GetItemsResponse>');
  });

  // 3.1-#103: POST — Tier 1
  it('3.1-#103: POST operation generates client method with body parameter', () => {
    const { contracts, client } = generateClientFromYaml(`
      openapi: "3.1.0"
      info: { title: Test, version: "1.0.0" }
      paths:
        /items:
          post:
            requestBody:
              required: true
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      name: { type: string }
                    required: [name]
            responses:
              "201":
                description: Created
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        id: { type: string }
                      required: [id]
    `);

    // Body type generated
    expect(contracts).toContain('export type PostItemsBody =');
    // Client: POST method
    expect(client).toContain('postItems:');
    expect(client).toContain('"POST"');
    // Body param in signature
    expect(client).toContain('body: PostItemsBody');
  });

  // 3.1-#104: PUT — Tier 1
  it('3.1-#104: PUT operation generates client method with body and path params', () => {
    const { client } = generateClientFromYaml(`
      openapi: "3.1.0"
      info: { title: Test, version: "1.0.0" }
      paths:
        /items/{id}:
          put:
            parameters:
              - name: id
                in: path
                required: true
                schema: { type: string }
            requestBody:
              required: true
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      name: { type: string }
            responses:
              "200": { description: Updated }
    `);

    expect(client).toContain('putItems');
    expect(client).toContain('"PUT"');
    // Both path param and body
    expect(client).toContain('(id: string, body:');
  });

  // 3.1-#105: PATCH — Tier 1
  it('3.1-#105: PATCH operation generates client method', () => {
    const { client } = generateClientFromYaml(`
      openapi: "3.1.0"
      info: { title: Test, version: "1.0.0" }
      paths:
        /items/{id}:
          patch:
            parameters:
              - name: id
                in: path
                required: true
                schema: { type: string }
            requestBody:
              required: true
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      name: { type: string }
            responses:
              "200": { description: Patched }
    `);

    expect(client).toContain('patchItems');
    expect(client).toContain('"PATCH"');
  });

  // 3.1-#106: DELETE — Tier 1
  it('3.1-#106: DELETE operation generates client method', () => {
    const { client } = generateClientFromYaml(`
      openapi: "3.1.0"
      info: { title: Test, version: "1.0.0" }
      paths:
        /items/{id}:
          delete:
            parameters:
              - name: id
                in: path
                required: true
                schema: { type: string }
            responses:
              "204": { description: Deleted }
    `);

    expect(client).toContain('deleteItems');
    expect(client).toContain('"DELETE"');
  });

  // 3.1-#107: OPTIONS — Tier 1
  it('3.1-#107: OPTIONS operation generates client method', () => {
    const { client } = generateClientFromYaml(`
      openapi: "3.1.0"
      info: { title: Test, version: "1.0.0" }
      paths:
        /items:
          options:
            responses:
              "200": { description: CORS }
    `);

    expect(client).toContain('optionsItems');
    expect(client).toContain('"OPTIONS"');
  });

  // 3.1-#108: HEAD — Tier 1
  it('3.1-#108: HEAD operation generates client method', () => {
    const { client } = generateClientFromYaml(`
      openapi: "3.1.0"
      info: { title: Test, version: "1.0.0" }
      paths:
        /items:
          head:
            responses:
              "200": { description: Headers }
    `);

    expect(client).toContain('headItems');
    expect(client).toContain('"HEAD"');
  });

  // 3.1-#109: TRACE — Tier 1
  it('3.1-#109: TRACE operation generates client method', () => {
    const { client } = generateClientFromYaml(`
      openapi: "3.1.0"
      info: { title: Test, version: "1.0.0" }
      paths:
        /items:
          trace:
            responses:
              "200": { description: Debug }
    `);

    expect(client).toContain('traceItems');
    expect(client).toContain('"TRACE"');
  });

  // Combined: all HTTP methods on the same path
  it('3.1-#102-#109: all 8 HTTP methods on one path generate 8 distinct methods', () => {
    const { client } = generateClientFromYaml(`
      openapi: "3.1.0"
      info: { title: Test, version: "1.0.0" }
      paths:
        /resource:
          get:
            responses:
              "200": { description: OK }
          post:
            responses:
              "201": { description: Created }
          put:
            responses:
              "200": { description: Updated }
          patch:
            responses:
              "200": { description: Patched }
          delete:
            responses:
              "204": { description: Deleted }
          options:
            responses:
              "200": { description: CORS }
          head:
            responses:
              "200": { description: Headers }
          trace:
            responses:
              "200": { description: Debug }
    `);

    expect(client).toContain('getResource');
    expect(client).toContain('postResource');
    expect(client).toContain('putResource');
    expect(client).toContain('patchResource');
    expect(client).toContain('deleteResource');
    expect(client).toContain('optionsResource');
    expect(client).toContain('headResource');
    expect(client).toContain('traceResource');
  });
});

// ── Path Operations: Metadata (3.1-#110-#114) ─────────────────────────────

describe('OpenAPI 3.1 — Operation Metadata (3.1-#110-#114)', () => {
  // 3.1-#110: operationId — Tier 1
  it('3.1-#110: operationId strategy uses operationId as method name', () => {
    const { client } = generateClientFromYaml(
      `
      openapi: "3.1.0"
      info: { title: Test, version: "1.0.0" }
      paths:
        /items:
          get:
            operationId: listAllItems
            responses:
              "200": { description: OK }
    `,
      { methodNameStrategy: 'operationId' }
    );

    expect(client).toContain('listAllItems:');
    // Should NOT use path-based name
    expect(client).not.toContain('getItems:');
  });

  it('3.1-#110: operationId with path-based strategy is ignored', () => {
    const { client } = generateClientFromYaml(
      `
      openapi: "3.1.0"
      info: { title: Test, version: "1.0.0" }
      paths:
        /items:
          get:
            operationId: listAllItems
            responses:
              "200": { description: OK }
    `,
      { methodNameStrategy: 'path-based' }
    );

    // Default path-based strategy ignores operationId
    expect(client).toContain('getItems:');
  });

  it('3.1-#110: operationId-with-fallback uses operationId when present', () => {
    const { client } = generateClientFromYaml(
      `
      openapi: "3.1.0"
      info: { title: Test, version: "1.0.0" }
      paths:
        /items:
          get:
            operationId: listItems
            responses:
              "200": { description: OK }
        /things:
          get:
            responses:
              "200": { description: OK }
    `,
      { methodNameStrategy: 'operationId-with-fallback' }
    );

    // First path: uses operationId
    expect(client).toContain('listItems:');
    // Second path: falls back to path-based
    expect(client).toContain('getThings:');
  });

  // 3.1-#111: summary — Tier 1
  it('3.1-#111: operation summary becomes JSDoc description', () => {
    const { client } = generateClientFromYaml(`
      openapi: "3.1.0"
      info: { title: Test, version: "1.0.0" }
      paths:
        /items:
          get:
            summary: Retrieve all items from the catalog
            responses:
              "200": { description: OK }
    `);

    // JSDoc with summary
    expect(client).toContain('Retrieve all items from the catalog');
  });

  // 3.1-#112: description — Tier 1
  it('3.1-#112: operation description appears in JSDoc after summary', () => {
    const { client } = generateClientFromYaml(`
      openapi: "3.1.0"
      info: { title: Test, version: "1.0.0" }
      paths:
        /items:
          get:
            summary: Get items
            description: Returns a paginated list of all available items
            responses:
              "200": { description: OK }
    `);

    // Both summary and description in JSDoc
    expect(client).toContain('Get items');
    expect(client).toContain('Returns a paginated list of all available items');
  });

  it('3.1-#112: description without summary still generates JSDoc', () => {
    const { client } = generateClientFromYaml(`
      openapi: "3.1.0"
      info: { title: Test, version: "1.0.0" }
      paths:
        /items:
          get:
            description: Fetches the complete catalog
            responses:
              "200": { description: OK }
    `);

    expect(client).toContain('Fetches the complete catalog');
  });

  // 3.1-#113: tags — Tier 1
  it('3.1-#113: operation tags become @category JSDoc annotations', () => {
    const { client } = generateClientFromYaml(`
      openapi: "3.1.0"
      info: { title: Test, version: "1.0.0" }
      paths:
        /items:
          get:
            tags: [catalog, public]
            summary: Get items
            responses:
              "200": { description: OK }
    `);

    // Tags become @category entries
    expect(client).toContain('@category catalog');
    expect(client).toContain('@category public');
  });

  // 3.1-#114: deprecated (operation) — Tier 1
  it('3.1-#114: deprecated operation adds @deprecated JSDoc tag', () => {
    const { client } = generateClientFromYaml(`
      openapi: "3.1.0"
      info: { title: Test, version: "1.0.0" }
      paths:
        /legacy/items:
          get:
            deprecated: true
            summary: Old endpoint
            responses:
              "200": { description: OK }
    `);

    expect(client).toContain('@deprecated');
    // Method still generated normally
    expect(client).toContain('getLegacyItems:');
  });

  // Combined: summary + description + tags + deprecated
  it('3.1-#111-#114: combined JSDoc with all metadata fields', () => {
    const { client } = generateClientFromYaml(`
      openapi: "3.1.0"
      info: { title: Test, version: "1.0.0" }
      paths:
        /legacy/items:
          get:
            summary: Legacy items endpoint
            description: Use the new /items endpoint instead
            tags: [legacy, deprecated]
            deprecated: true
            responses:
              "200": { description: OK }
    `);

    // Full JSDoc: summary, description, category tags, @deprecated
    expect(client).toContain('Legacy items endpoint');
    expect(client).toContain('Use the new /items endpoint instead');
    expect(client).toContain('@category legacy');
    expect(client).toContain('@category deprecated');
    expect(client).toContain('@deprecated');
  });
});
