import type { AnalyzedOperation } from '../analyzer/path-analyzer.js';

/**
 * Reserved type names used by the generated output's built-in classes,
 * functions, and types. User-defined schema names that collide with these
 * are automatically renamed with a suffix to prevent duplicate identifiers.
 */
export const RESERVED_TYPE_NAMES: ReadonlySet<string> = new Set([
  // Classes in contracts.ts
  'StreamResponse',
  'ErrorResponse',
  'ApiError',
  'UnspecifiedApiError',
  'DefaultApiError',
  'RequesterFailError',
  // Functions in contracts.ts
  'streamResponse',
  'errorResponse',
  // Types / functions in client.ts
  'Requester',
  'isDefinedError',
  'decorateWithErrors',
  'ApiClient',
  // Interface in contracts.ts (when file uploads present)
  'FileInput',
]);

/**
 * Sanitize a schema type name by converting dot-separated segments into
 * PascalCase. Names without dots pass through unchanged.
 *
 * "Api.Error" → "ApiError", "Simple" → "Simple"
 */
export function sanitizeTypeName(name: string): string {
  if (!name.includes('.')) return name;
  return name
    .split('.')
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join('');
}

/**
 * Build a mapping of sanitized schema names → renamed names for any that
 * collide with reserved type names.
 */
export function buildSchemaRenameMap(
  schemaNames: Iterable<string>,
  reserved: ReadonlySet<string>,
  suffix = 'Model'
): Map<string, string> {
  const renameMap = new Map<string, string>();
  for (const name of schemaNames) {
    const sanitized = sanitizeTypeName(name);
    if (reserved.has(sanitized)) {
      renameMap.set(sanitized, `${sanitized}${suffix}`);
    }
  }
  return renameMap;
}

/**
 * Convert a string to PascalCase, handling camelCase, kebab-case, snake_case,
 * and colon-separated segments.
 */
export function toPascalCase(str: string): string {
  return str
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .split(/[-_\s:]/)
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
}

/**
 * Build a PascalCase type-name prefix from an operation's method + path.
 * get + /api/v1/products → "GetApiV1Products"
 */
export function getOperationTypePrefix(op: AnalyzedOperation): string {
  const methodPascal = op.method.charAt(0).toUpperCase() + op.method.slice(1).toLowerCase();

  const segments = op.path
    .split('/')
    .filter((s) => s.length > 0)
    .map((s) => {
      const cleaned = s.replace(/[{}]/g, '');
      return toPascalCase(cleaned);
    });

  return methodPascal + segments.join('');
}

/**
 * Determine the success return type for an operation.
 */
export function getSuccessType(op: AnalyzedOperation): string {
  const successResponses = op.responses.filter((r) => r.isSuccess);

  if (successResponses.length === 0) {
    return 'unknown';
  }

  const noContent = successResponses.find((r) => r.tsType === 'void');
  const hasOnlyNoContent = noContent && successResponses.every((r) => r.tsType === 'void');
  if (hasOnlyNoContent) {
    return 'void';
  }

  const withSchema = successResponses.filter((r) => r.tsType !== 'void');

  if (withSchema.length === 0) {
    return 'void';
  }

  const prefix = getOperationTypePrefix(op);
  const types = withSchema.map(() => `${prefix}Response`);

  const unique = [...new Set(types)];
  return unique.join(' | ');
}

/**
 * Determine the error type name for an operation.
 */
export function getErrorType(op: AnalyzedOperation): string {
  const prefix = getOperationTypePrefix(op);
  const errorResponses = op.responses.filter((r) => !r.isSuccess && r.statusCode !== 'default');
  if (errorResponses.length === 0) {
    return 'never';
  }
  return `${prefix}Errors`;
}

/**
 * Generate the auto-generated header comment.
 */
export function makeHeader(version: string): string {
  return `// Auto-generated by genoc from OpenAPI ${version} spec. DO NOT EDIT.`;
}
