import type { AnalyzedOperation } from '../analyzer/path-analyzer.js';
import type { SchemaObject } from '../types/openapi.js';

/**
 * Reserved type names used by the generated output's built-in classes,
 * functions, and types. User-defined schema names that collide with these
 * are automatically renamed with a suffix to prevent duplicate identifiers.
 */
export const RESERVED_TYPE_NAMES: ReadonlySet<string> = new Set([
  // Classes in contracts.ts
  'StreamResponse',
  'ErrorResponse',
  'ApiError',
  'UnspecifiedApiError',
  'DefaultApiError',
  'RequesterFailError',
  // Types / functions in client.ts
  'Requester',
  'isDefinedError',
  'decorateWithErrors',
  'ApiClient',
  // Interface in contracts.ts (when file uploads present)
  'FileInput',
]);

/** Default module specifier generated code imports shared runtime classes from. */
export const DEFAULT_RUNTIME_IMPORT_PATH = 'genoc/runtime';

/**
 * Sanitize a schema type name by converting dot-separated segments into
 * PascalCase. Names without dots pass through unchanged.
 *
 * "Api.Error" → "ApiError", "Simple" → "Simple"
 */
export function sanitizeTypeName(name: string): string {
  if (!name.includes('.')) return name;
  return name
    .split('.')
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join('');
}

/**
 * Build a mapping of sanitized schema names → renamed names for any that
 * collide with reserved type names.
 */
export function buildSchemaRenameMap(
  schemaNames: Iterable<string>,
  reserved: ReadonlySet<string>,
  suffix = 'Model'
): Map<string, string> {
  const renameMap = new Map<string, string>();
  for (const name of schemaNames) {
    const sanitized = sanitizeTypeName(name);
    if (reserved.has(sanitized)) {
      renameMap.set(sanitized, `${sanitized}${suffix}`);
    }
  }
  return renameMap;
}

/**
 * Convert a string to PascalCase, handling camelCase, kebab-case, snake_case,
 * and colon-separated segments.
 */
export function toPascalCase(str: string): string {
  return str
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .split(/[-_\s:]/)
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
}

/**
 * Build a PascalCase type-name prefix from an operation's method + path.
 * get + /api/v1/products → "GetApiV1Products"
 */
export function getOperationTypePrefix(op: AnalyzedOperation): string {
  const methodPascal = op.method.charAt(0).toUpperCase() + op.method.slice(1).toLowerCase();

  const segments = op.path
    .split('/')
    .filter((s) => s.length > 0)
    .map((s) => {
      const cleaned = s.replace(/[{}]/g, '');
      return toPascalCase(cleaned);
    });

  return methodPascal + segments.join('');
}

/**
 * Determine the success return type for an operation.
 */
export function getSuccessType(op: AnalyzedOperation): string {
  const successResponses = op.responses.filter((r) => r.isSuccess);

  if (successResponses.length === 0) {
    return 'unknown';
  }

  const noContent = successResponses.find((r) => r.tsType === 'void');
  const hasOnlyNoContent = noContent && successResponses.every((r) => r.tsType === 'void');
  if (hasOnlyNoContent) {
    return 'void';
  }

  const withSchema = successResponses.filter((r) => r.tsType !== 'void');

  if (withSchema.length === 0) {
    return 'void';
  }

  const prefix = getOperationTypePrefix(op);
  const types = withSchema.map(() => `${prefix}Response`);

  const unique = [...new Set(types)];
  return unique.join(' | ');
}

/**
 * Determine the error type name for an operation.
 */
export function getErrorType(op: AnalyzedOperation): string {
  const prefix = getOperationTypePrefix(op);
  const errorResponses = op.responses.filter((r) => !r.isSuccess && r.statusCode !== 'default');
  if (errorResponses.length === 0) {
    return 'never';
  }
  return `${prefix}Errors`;
}

/**
 * Generate the auto-generated header comment.
 */
export function makeHeader(version: string): string {
  return `// Auto-generated by genoc from OpenAPI ${version} spec. DO NOT EDIT.`;
}

/**
 * Sanitize free-form text for safe inclusion inside a JSDoc comment.
 *
 * Normalizes CRLF to LF, flattens remaining newlines into single spaces,
 * escapes the comment-closing sequence (asterisk + slash) as `*\/`, and
 * trims leading/trailing whitespace. No other transformation is applied —
 * no HTML stripping, no markdown processing, no wrapping.
 */
export function sanitizeJsDocText(text: string): string {
  return text.replace(/\r\n/g, '\n').replace(/\n/g, ' ').replace(/\*\//g, '*\\/').trim();
}

/**
 * Format an arbitrary metadata value for a JSDoc tag using JSON.stringify
 * (no indent). Returns `null` when stringify yields `undefined` (e.g. for
 * `undefined` or function values) — callers should skip the tag entirely.
 */
export function formatJsDocValue(value: unknown): string | null {
  const json = JSON.stringify(value);
  return json === undefined ? null : json;
}

/**
 * Build the ordered JSDoc content segments for a schema-backed property.
 *
 * Order (frozen): description → `@deprecated` → `@default` → `@example`(s)
 * → `@title`. Segments are skipped when their value is absent, empty, or
 * whitespace-only. Sanitization is applied AFTER stringification for
 * `@default` / `@example` values.
 */
export function buildFieldJsDocLines(schema: SchemaObject): string[] {
  const lines: string[] = [];

  if (schema.description !== undefined && schema.description.trim() !== '') {
    lines.push(sanitizeJsDocText(schema.description));
  }

  if (schema.deprecated === true) {
    lines.push('@deprecated');
  }

  if (schema.default !== undefined) {
    const formatted = formatJsDocValue(schema.default);
    if (formatted !== null) {
      lines.push(`@default ${sanitizeJsDocText(formatted)}`);
    }
  }

  if (schema.example !== undefined) {
    const formatted = formatJsDocValue(schema.example);
    if (formatted !== null) {
      lines.push(`@example ${sanitizeJsDocText(formatted)}`);
    }
  }

  if (schema.examples !== undefined) {
    for (const value of schema.examples) {
      const formatted = formatJsDocValue(value);
      if (formatted !== null) {
        lines.push(`@example ${sanitizeJsDocText(formatted)}`);
      }
    }
  }

  if (schema.title) {
    lines.push(`@title ${sanitizeJsDocText(schema.title)}`);
  }

  return lines;
}

/**
 * Render a schema's JSDoc metadata as a complete comment block.
 *
 * 0 segments → `''`; exactly 1 segment → single-line `/** text *\/`;
 * ≥2 segments → multiline block with a blank ` *` line between segments.
 */
export function buildTypeJsDoc(schema: SchemaObject): string {
  const lines = buildFieldJsDocLines(schema);
  if (lines.length === 0) return '';
  if (lines.length === 1) return `/** ${lines[0]} */`;
  return `/**\n${lines.map((line) => ` * ${line}`).join('\n *\n')}\n */`;
}
