import { describe, expect, it } from 'vitest';

import { generateContracts } from '../../src/generator/contracts-generator.js';
import { RefResolver } from '../../src/parser/ref-resolver.js';
import type {
  OpenAPIDocument,
  SecuritySchemeObject,
  ServerVariableObject,
} from '../../src/types/openapi.js';

function createDoc(overrides?: Partial<OpenAPIDocument>): OpenAPIDocument {
  return {
    openapi: '3.1.0',
    info: { title: 'Test', version: '1.0.0' },
    ...overrides,
  };
}

function makeResolver(doc: OpenAPIDocument): RefResolver {
  return new RefResolver(doc);
}

describe('generateContracts', () => {
  describe('header', () => {
    it('includes auto-generated header comment', () => {
      const doc = createDoc();
      const result = generateContracts(doc, makeResolver(doc));
      expect(
        result.startsWith('// Auto-generated by genoc from OpenAPI 3.1.0 spec. DO NOT EDIT.')
      ).toBe(true);
    });
  });

  describe('Section 1: Schema types from components/schemas', () => {
    it('generates interface for object schema', () => {
      const doc = createDoc({
        components: {
          schemas: {
            Product: {
              type: 'object',
              properties: {
                name: { type: 'string' },
                price: { type: 'number' },
              },
              required: ['name', 'price'],
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('export type Product = {');
      expect(result).toContain(' name: string;');
      expect(result).toContain(' price: number;');
      expect(result).toContain('}');
    });

    it('generates type alias for string enum (literal union, NOT enum keyword)', () => {
      const doc = createDoc({
        components: {
          schemas: {
            Color: { type: 'string', enum: ['red', 'green', 'blue'] },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain("export type Color = 'red' | 'green' | 'blue';");
      expect(result).not.toContain('enum Color');
    });

    it('generates type alias for numeric enum', () => {
      const doc = createDoc({
        components: {
          schemas: {
            Priority: { type: 'integer', enum: [1, 2, 3] },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('export type Priority = 1 | 2 | 3;');
    });

    it('generates type alias for primitive schema', () => {
      const doc = createDoc({
        components: {
          schemas: {
            Status: { type: 'string' },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('export type Status = string;');
    });

    it('generates intersection type for allOf', () => {
      const doc = createDoc({
        components: {
          schemas: {
            Base: {
              type: 'object',
              properties: { id: { type: 'string' } },
              required: ['id'],
            },
            Extended: {
              allOf: [
                { $ref: '#/components/schemas/Base' },
                {
                  type: 'object',
                  properties: { name: { type: 'string' } },
                  required: ['name'],
                },
              ],
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('export type Extended = Base &');
    });

    it('generates union type for oneOf', () => {
      const doc = createDoc({
        components: {
          schemas: {
            Success: {
              type: 'object',
              properties: { data: { type: 'string' } },
            },
            Error: {
              type: 'object',
              properties: { message: { type: 'string' } },
            },
            Result: {
              oneOf: [
                { $ref: '#/components/schemas/Success' },
                { $ref: '#/components/schemas/Error' },
              ],
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('export type Result = Success | Error;');
    });

    it('generates union type for anyOf', () => {
      const doc = createDoc({
        components: {
          schemas: {
            Cat: {
              type: 'object',
              properties: { meow: { type: 'boolean' } },
            },
            Dog: {
              type: 'object',
              properties: { bark: { type: 'boolean' } },
            },
            Pet: {
              anyOf: [{ $ref: '#/components/schemas/Cat' }, { $ref: '#/components/schemas/Dog' }],
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('export type Pet = Cat | Dog;');
    });

    it('generates array type alias', () => {
      const doc = createDoc({
        components: {
          schemas: {
            Tag: { type: 'string' },
            TagList: {
              type: 'array',
              items: { $ref: '#/components/schemas/Tag' },
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('export type TagList = Tag[];');
    });

    it('generates nullable type', () => {
      const doc = createDoc({
        components: {
          schemas: {
            MaybeString: { type: 'string', nullable: true },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('export type MaybeString = string | null;');
    });

    it('adds JSDoc from description field', () => {
      const doc = createDoc({
        components: {
          schemas: {
            Product: {
              type: 'object',
              description: 'A product in the catalog',
              properties: { name: { type: 'string' } },
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('/** A product in the catalog */');
    });

    it('produces no JSDoc when description is absent', () => {
      const doc = createDoc({
        components: {
          schemas: {
            Plain: {
              type: 'object',
              properties: { value: { type: 'string' } },
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('export type Plain = {');
      expect(result).not.toContain('/**');
    });

    it('sorts types topologically so referenced types appear first', () => {
      const doc = createDoc({
        components: {
          schemas: {
            OrderItem: {
              type: 'object',
              properties: {
                product: { $ref: '#/components/schemas/Product' },
                quantity: { type: 'integer' },
              },
              required: ['product', 'quantity'],
            },
            Product: {
              type: 'object',
              properties: {
                name: { type: 'string' },
                price: { type: 'number' },
              },
              required: ['name', 'price'],
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      const productPos = result.indexOf('export type Product');
      const orderItemPos = result.indexOf('export type OrderItem');
      expect(productPos).toBeLessThan(orderItemPos);
    });

    it('produces no schema types when components.schemas is empty', () => {
      const doc = createDoc({ components: { schemas: {} } });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).not.toMatch(/export interface \w+/);
      expect(result).not.toMatch(/export type \w+ =/);
    });
  });

  describe('Section 2: Parameter types per operation', () => {
    it('generates query parameter type with optional fields', () => {
      const doc = createDoc({
        paths: {
          '/api/v1/products': {
            get: {
              parameters: [
                { name: 'page', in: 'query', schema: { type: 'integer' } },
                { name: 'limit', in: 'query', schema: { type: 'integer' } },
              ],
              responses: { '200': { description: 'OK' } },
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('export type GetApiV1ProductsQuery =');
      expect(result).toContain('page?: number');
      expect(result).toContain('limit?: number');
    });

    it('marks required query params without ?', () => {
      const doc = createDoc({
        paths: {
          '/search': {
            get: {
              parameters: [
                {
                  name: 'q',
                  in: 'query',
                  required: true,
                  schema: { type: 'string' },
                },
              ],
              responses: { '200': { description: 'OK' } },
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('q: string');
      expect(result).not.toContain('q?:');
    });

    it('does not generate query type for operations without query params', () => {
      const doc = createDoc({
        paths: {
          '/users': {
            get: {
              responses: { '200': { description: 'OK' } },
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).not.toContain('Query =');
    });
  });

  describe('Section 2b: Header parameter types per operation', () => {
    it('generates header type with required + optional fields', () => {
      const doc = createDoc({
        paths: {
          '/api/v1/data': {
            get: {
              parameters: [
                {
                  name: 'X-Request-ID',
                  in: 'header',
                  required: true,
                  schema: { type: 'string' },
                },
                {
                  name: 'Authorization',
                  in: 'header',
                  schema: { type: 'string' },
                },
              ],
              responses: { '200': { description: 'OK' } },
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('export type GetApiV1DataHeaders =');
      expect(result).toContain('"X-Request-ID": string');
      expect(result).toContain('Authorization?: string');
    });

    it('maps typed headers (integer, enum) to correct TS types', () => {
      const doc = createDoc({
        paths: {
          '/api/v1/items': {
            get: {
              parameters: [
                {
                  name: 'X-Retry-Count',
                  in: 'header',
                  schema: { type: 'integer' },
                },
                {
                  name: 'X-Version',
                  in: 'header',
                  schema: { type: 'string', enum: ['v1', 'v2'] },
                },
              ],
              responses: { '200': { description: 'OK' } },
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('export type GetApiV1ItemsHeaders =');
      expect(result).toContain('"X-Retry-Count"?: number');
      expect(result).toContain('"X-Version"?:');
      expect(result).toContain("'v1' | 'v2'");
    });

    it('does not generate Headers type for operations without header params', () => {
      const doc = createDoc({
        paths: {
          '/users': {
            get: {
              parameters: [{ name: 'page', in: 'query', schema: { type: 'integer' } }],
              responses: { '200': { description: 'OK' } },
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).not.toContain('export type GetApiV1DataHeaders =');
    });

    it('quotes header names with special characters', () => {
      const doc = createDoc({
        paths: {
          '/api/v1/data': {
            get: {
              parameters: [
                {
                  name: 'X-Custom-Header',
                  in: 'header',
                  required: true,
                  schema: { type: 'string' },
                },
                {
                  name: 'X-Special.Chars',
                  in: 'header',
                  schema: { type: 'string' },
                },
              ],
              responses: { '200': { description: 'OK' } },
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('"X-Custom-Header": string');
      expect(result).toContain('"X-Special.Chars"?: string');
    });

    it('leaves simple header names unquoted', () => {
      const doc = createDoc({
        paths: {
          '/api/v1/data': {
            get: {
              parameters: [
                {
                  name: 'Authorization',
                  in: 'header',
                  required: true,
                  schema: { type: 'string' },
                },
              ],
              responses: { '200': { description: 'OK' } },
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('Authorization: string');
      expect(result).not.toContain('"Authorization"');
    });
  });

  describe('Section 3: Request body types per operation', () => {
    it('generates request body type from inline schema', () => {
      const doc = createDoc({
        paths: {
          '/api/v1/products': {
            post: {
              requestBody: {
                content: {
                  'application/json': {
                    schema: {
                      type: 'object',
                      properties: {
                        name: { type: 'string' },
                        price: { type: 'number' },
                      },
                      required: ['name', 'price'],
                    },
                  },
                },
              },
              responses: { '201': { description: 'Created' } },
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('export type PostApiV1ProductsBody =');
      expect(result).toContain('name: string');
      expect(result).toContain('price: number');
    });

    it('generates request body type from $ref', () => {
      const doc = createDoc({
        components: {
          schemas: {
            CreateProduct: {
              type: 'object',
              properties: {
                name: { type: 'string' },
              },
              required: ['name'],
            },
          },
        },
        paths: {
          '/products': {
            post: {
              requestBody: {
                content: {
                  'application/json': {
                    schema: { $ref: '#/components/schemas/CreateProduct' },
                  },
                },
              },
              responses: { '201': { description: 'Created' } },
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('export type PostProductsBody = CreateProduct;');
    });

    it('does not generate body type for operations without request body', () => {
      const doc = createDoc({
        paths: {
          '/users': {
            get: {
              responses: { '200': { description: 'OK' } },
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).not.toContain('Body =');
    });
  });

  describe('Section 4: Response types per operation', () => {
    it('generates success response type from schema', () => {
      const doc = createDoc({
        components: {
          schemas: {
            Product: {
              type: 'object',
              properties: { name: { type: 'string' } },
            },
          },
        },
        paths: {
          '/api/v1/products': {
            get: {
              responses: {
                '200': {
                  description: 'OK',
                  content: {
                    'application/json': {
                      schema: {
                        type: 'array',
                        items: { $ref: '#/components/schemas/Product' },
                      },
                    },
                  },
                },
              },
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('export type GetApiV1ProductsResponse = Product[];');
    });

    it('generates error types per status code', () => {
      const doc = createDoc({
        components: {
          schemas: {
            Product: {
              type: 'object',
              properties: { name: { type: 'string' } },
            },
            BadRequestError: {
              type: 'object',
              properties: { message: { type: 'string' } },
            },
            NotFoundError: {
              type: 'object',
              properties: { message: { type: 'string' } },
            },
          },
        },
        paths: {
          '/api/v1/products/{productId}': {
            get: {
              parameters: [
                {
                  name: 'productId',
                  in: 'path',
                  required: true,
                  schema: { type: 'string' },
                },
              ],
              responses: {
                '200': {
                  description: 'OK',
                  content: {
                    'application/json': {
                      schema: { $ref: '#/components/schemas/Product' },
                    },
                  },
                },
                '400': {
                  description: 'Bad Request',
                  content: {
                    'application/json': {
                      schema: { $ref: '#/components/schemas/BadRequestError' },
                    },
                  },
                },
                '404': {
                  description: 'Not Found',
                  content: {
                    'application/json': {
                      schema: { $ref: '#/components/schemas/NotFoundError' },
                    },
                  },
                },
              },
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('export type GetApiV1ProductsProductIdResponse = Product;');
      expect(result).toContain('export type GetApiV1ProductsProductIdError400 = BadRequestError;');
      expect(result).toContain('export type GetApiV1ProductsProductIdError404 = NotFoundError;');
    });

    it('handles colon in path for type name generation', () => {
      const doc = createDoc({
        components: {
          schemas: {
            Product: {
              type: 'object',
              properties: { name: { type: 'string' } },
            },
          },
        },
        paths: {
          '/api/v1/AsyncOperations/{operationId}:recall': {
            get: {
              parameters: [
                {
                  name: 'operationId',
                  in: 'path',
                  required: true,
                  schema: { type: 'string' },
                },
              ],
              responses: {
                '200': {
                  description: 'OK',
                  content: {
                    'application/json': {
                      schema: { $ref: '#/components/schemas/Product' },
                    },
                  },
                },
              },
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain(
        'export type GetApiV1AsyncOperationsOperationIdRecallResponse = Product;'
      );
      expect(result).not.toContain('GetApiV1AsyncOperationsOperationId:Recall');
      expect(result).toContain('Recall');
    });

    it('generates error union type combining all error statuses', () => {
      const doc = createDoc({
        paths: {
          '/items': {
            get: {
              responses: {
                '200': { description: 'OK' },
                '400': { description: 'Bad Request' },
                '404': { description: 'Not Found' },
              },
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain(
        'export type GetItemsErrors = ApiError<400, GetItemsError400> | ApiError<404, GetItemsError404>;'
      );
    });

    it('uses unknown for error types without schema', () => {
      const doc = createDoc({
        paths: {
          '/items': {
            get: {
              responses: {
                '200': { description: 'OK' },
                '500': { description: 'Server Error' },
              },
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('export type GetItemsError500 = unknown;');
    });

    it("generates DefaultError type and DefaultApiError class for 'default' response", () => {
      const doc = createDoc({
        paths: {
          '/items': {
            get: {
              responses: {
                '200': { description: 'OK' },
                default: { description: 'Unexpected error' },
              },
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('export type GetItemsDefaultError = unknown;');
      expect(result).toContain('export class DefaultApiError<TData> extends Error');
      expect(result).not.toContain('ErrorDefault');
      expect(result).not.toContain('Errors =');
    });

    it('generates typed DefaultError for default response with schema', () => {
      const doc = createDoc({
        components: {
          schemas: {
            ErrorBody: {
              type: 'object',
              properties: { message: { type: 'string' } },
            },
          },
        },
        paths: {
          '/items': {
            get: {
              responses: {
                '200': { description: 'OK' },
                default: {
                  description: 'Error',
                  content: {
                    'application/json': {
                      schema: { $ref: '#/components/schemas/ErrorBody' },
                    },
                  },
                },
              },
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('export type GetItemsDefaultError = ErrorBody;');
      expect(result).toContain('export class DefaultApiError<TData> extends Error');
    });

    it('does not generate DefaultApiError when no operation has default response', () => {
      const doc = createDoc({
        paths: {
          '/items': {
            get: {
              responses: {
                '200': { description: 'OK' },
                '400': { description: 'Bad Request' },
              },
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).not.toContain('DefaultApiError');
      expect(result).not.toContain('DefaultError');
    });
  });

  describe('Section 5: ApiError class', () => {
    it('always includes ApiError class even for empty doc', () => {
      const doc = createDoc();
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain(
        'export class ApiError<TStatus extends number, TData> extends Error'
      );
    });

    it('ApiError has correct constructor signature', () => {
      const doc = createDoc();
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('public readonly status: TStatus');
      expect(result).toContain('public readonly data: TData');
      expect(result).toContain('message: string');
    });

    it("ApiError sets this.name to 'ApiError'", () => {
      const doc = createDoc();
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('this.name = "ApiError"');
    });
  });

  describe('empty document', () => {
    it('generates header and error handling constructs', () => {
      const doc = createDoc();
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('// Auto-generated by genoc from OpenAPI 3.1.0 spec. DO NOT EDIT.');
      expect(result).toContain('export class ApiError');
      expect(result).toContain('export class ErrorResponse');
      expect(result).toContain('export function errorResponse');
      expect(result).toContain('export class RequesterFailError');
      const lines = result.split('\n');
      expect(lines.length).toBeGreaterThan(25);
    });
  });

  describe('error handling constructs', () => {
    it('includes ErrorResponse class', () => {
      const doc = createDoc();
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('export class ErrorResponse');
    });

    it('includes errorResponse() helper', () => {
      const doc = createDoc();
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('export function errorResponse(');
    });

    it('includes RequesterFailError class', () => {
      const doc = createDoc();
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('export class RequesterFailError extends Error');
    });
  });

  describe('full integration', () => {
    it('generates complete contracts with all sections', () => {
      const doc: OpenAPIDocument = {
        openapi: '3.1.0',
        info: { title: 'Store API', version: '1.0.0' },
        components: {
          schemas: {
            Product: {
              type: 'object',
              description: 'A product',
              properties: {
                id: { type: 'string' },
                name: { type: 'string' },
                price: { type: 'number' },
              },
              required: ['id', 'name', 'price'],
            },
            CreateProductInput: {
              type: 'object',
              properties: {
                name: { type: 'string' },
                price: { type: 'number' },
              },
              required: ['name', 'price'],
            },
            ErrorBody: {
              type: 'object',
              properties: {
                code: { type: 'integer' },
                message: { type: 'string' },
              },
              required: ['code', 'message'],
            },
            ProductStatus: {
              type: 'string',
              enum: ['available', 'discontinued'],
            },
          },
        },
        paths: {
          '/api/v1/products': {
            get: {
              operationId: 'listProducts',
              summary: 'List products',
              parameters: [
                { name: 'page', in: 'query', schema: { type: 'integer' } },
                { name: 'limit', in: 'query', schema: { type: 'integer' } },
              ],
              responses: {
                '200': {
                  description: 'Product list',
                  content: {
                    'application/json': {
                      schema: {
                        type: 'array',
                        items: { $ref: '#/components/schemas/Product' },
                      },
                    },
                  },
                },
                '400': {
                  description: 'Bad request',
                  content: {
                    'application/json': {
                      schema: { $ref: '#/components/schemas/ErrorBody' },
                    },
                  },
                },
              },
            },
            post: {
              operationId: 'createProduct',
              summary: 'Create product',
              requestBody: {
                content: {
                  'application/json': {
                    schema: { $ref: '#/components/schemas/CreateProductInput' },
                  },
                },
              },
              responses: {
                '201': {
                  description: 'Created',
                  content: {
                    'application/json': {
                      schema: { $ref: '#/components/schemas/Product' },
                    },
                  },
                },
                '400': {
                  description: 'Bad request',
                  content: {
                    'application/json': {
                      schema: { $ref: '#/components/schemas/ErrorBody' },
                    },
                  },
                },
              },
            },
          },
        },
      };

      const result = generateContracts(doc, makeResolver(doc));

      expect(result).toContain('// Auto-generated by genoc from OpenAPI 3.1.0 spec. DO NOT EDIT.');

      expect(result).toContain('export type Product = {');
      expect(result).toContain(' id: string;');
      expect(result).toContain(' name: string;');
      expect(result).toContain(' price: number;');

      expect(result).toContain('export type CreateProductInput = {');
      expect(result).toContain('export type ErrorBody = {');
      expect(result).toContain("export type ProductStatus = 'available' | 'discontinued';");

      const productPos = result.indexOf('export type Product');
      const createInputPos = result.indexOf('export type CreateProductInput');
      expect(productPos).toBeLessThan(createInputPos);

      expect(result).toContain('export type GetApiV1ProductsQuery =');
      expect(result).toContain('page?: number');
      expect(result).toContain('limit?: number');

      expect(result).toContain('export type PostApiV1ProductsBody = CreateProductInput;');

      expect(result).toContain('export type GetApiV1ProductsResponse = Product[];');
      expect(result).toContain('export type GetApiV1ProductsError400 = ErrorBody;');
      expect(result).toContain(
        'export type GetApiV1ProductsErrors = ApiError<400, GetApiV1ProductsError400>;'
      );

      expect(result).toContain('export type PostApiV1ProductsResponse = Product;');
      expect(result).toContain('export type PostApiV1ProductsError400 = ErrorBody;');

      expect(result).toContain('export class ApiError<TStatus extends number, TData>');
    });

    it('handles operations with path parameters in type names', () => {
      const doc = createDoc({
        paths: {
          '/users/{userId}/posts/{postId}': {
            get: {
              parameters: [
                {
                  name: 'userId',
                  in: 'path',
                  required: true,
                  schema: { type: 'string' },
                },
                {
                  name: 'postId',
                  in: 'path',
                  required: true,
                  schema: { type: 'string' },
                },
              ],
              responses: { '200': { description: 'OK' } },
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('export type GetUsersUserIdPostsPostIdResponse');
    });
  });

  describe('Section 1b: Security scheme types', () => {
    it('generates type for apiKey security scheme', () => {
      const doc = createDoc({
        components: {
          securitySchemes: {
            api_key: {
              type: 'apiKey',
              name: 'X-API-Key',
              in: 'header',
            } as SecuritySchemeObject,
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain(
        'export type ApiKeyAuth = { type: "apiKey"; name: "X-API-Key"; in: "header" };'
      );
    });

    it('generates type for http/bearer security scheme', () => {
      const doc = createDoc({
        components: {
          securitySchemes: {
            bearer: {
              type: 'http',
              scheme: 'bearer',
              bearerFormat: 'JWT',
            } as SecuritySchemeObject,
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain(
        'export type BearerAuth = { type: "http"; scheme: "bearer"; bearerFormat: "JWT" };'
      );
    });

    it('generates type for oauth2 security scheme with flows', () => {
      const doc = createDoc({
        components: {
          securitySchemes: {
            oauth2: {
              type: 'oauth2',
              flows: {
                authorizationCode: {
                  authorizationUrl: 'https://example.com/oauth/authorize',
                  tokenUrl: 'https://example.com/oauth/token',
                  scopes: {
                    'read:pets': 'Read pets',
                    'write:pets': 'Write pets',
                  },
                },
              },
            } as SecuritySchemeObject,
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('export type Oauth2Auth = { type: "oauth2"');
      expect(result).toContain('authorizationUrl: "https://example.com/oauth/authorize"');
      expect(result).toContain('tokenUrl: "https://example.com/oauth/token"');
      expect(result).toContain('"read:pets": "Read pets"');
      expect(result).toContain('"write:pets": "Write pets"');
    });

    it('generates union type for multiple security schemes', () => {
      const doc = createDoc({
        components: {
          securitySchemes: {
            api_key: {
              type: 'apiKey',
              name: 'X-API-Key',
              in: 'header',
            } as SecuritySchemeObject,
            bearer: {
              type: 'http',
              scheme: 'bearer',
            } as SecuritySchemeObject,
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('export type ApiKeyAuth =');
      expect(result).toContain('export type BearerAuth =');
      expect(result).toContain('export type SecuritySchemes = ApiKeyAuth | BearerAuth;');
    });

    it('does not generate SecuritySchemes union for a single scheme', () => {
      const doc = createDoc({
        components: {
          securitySchemes: {
            api_key: {
              type: 'apiKey',
              name: 'X-API-Key',
              in: 'header',
            } as SecuritySchemeObject,
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('export type ApiKeyAuth =');
      expect(result).not.toContain('export type SecuritySchemes =');
    });

    it('generates no security types when securitySchemes is absent', () => {
      const doc = createDoc();
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).not.toContain('Auth =');
      expect(result).not.toContain('SecuritySchemes =');
    });

    it('generates no security types when securitySchemes is empty', () => {
      const doc = createDoc({
        components: { securitySchemes: {} },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).not.toContain('Auth =');
      expect(result).not.toContain('SecuritySchemes =');
    });

    it('generates type for openIdConnect security scheme', () => {
      const doc = createDoc({
        components: {
          securitySchemes: {
            oidc: {
              type: 'openIdConnect',
              openIdConnectUrl: 'https://example.com/.well-known/openid-configuration',
            } as SecuritySchemeObject,
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('export type OidcAuth = { type: "openIdConnect"');
      expect(result).toContain(
        'openIdConnectUrl: "https://example.com/.well-known/openid-configuration"'
      );
    });

    it('includes JSDoc description from security scheme', () => {
      const doc = createDoc({
        components: {
          securitySchemes: {
            api_key: {
              type: 'apiKey',
              description: 'API key for authentication',
              name: 'X-API-Key',
              in: 'header',
            } as SecuritySchemeObject,
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('/** API key for authentication */');
    });
  });

  describe('Section 1c: Server variable types', () => {
    it('generates ServerParams with enum union type and JSDoc default', () => {
      const doc = createDoc({
        servers: [
          {
            url: 'https://{environment}.api.example.com/{version}',
            variables: {
              environment: {
                default: 'production',
                enum: ['production', 'staging', 'development'],
              } as ServerVariableObject,
              version: {
                default: 'v1',
              } as ServerVariableObject,
            },
          },
        ],
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('export interface ServerParams {');
      expect(result).toContain('/** @default production */');
      expect(result).toContain('environment: "production" | "staging" | "development";');
      expect(result).toContain('/** @default v1 */');
      expect(result).toContain('version: string;');
    });

    it('generates string type for variables without enum', () => {
      const doc = createDoc({
        servers: [
          {
            url: 'https://{region}.example.com',
            variables: {
              region: {
                default: 'us-east-1',
                description: 'Deployment region',
              } as ServerVariableObject,
            },
          },
        ],
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('export interface ServerParams {');
      expect(result).toContain('/** Deployment region @default us-east-1 */');
      expect(result).toContain('region: string;');
    });

    it('generates numbered types for multiple servers with variables', () => {
      const doc = createDoc({
        servers: [
          {
            url: 'https://{env}.api.example.com',
            variables: {
              env: {
                default: 'prod',
              } as ServerVariableObject,
            },
          },
          {
            url: 'https://{region}.cdn.example.com',
            variables: {
              region: {
                default: 'us',
              } as ServerVariableObject,
            },
          },
        ],
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('export interface Server1Params {');
      expect(result).toContain('env: string;');
      expect(result).toContain('export interface Server2Params {');
      expect(result).toContain('region: string;');
    });

    it('skips servers without variables', () => {
      const doc = createDoc({
        servers: [
          {
            url: 'https://api.example.com',
            description: 'Production server',
          },
        ],
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).not.toContain('ServerParams');
      expect(result).not.toContain('Server1Params');
    });

    it('generates no server types when servers is absent', () => {
      const doc = createDoc();
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).not.toContain('type Server');
      expect(result).not.toContain('ServerParams');
    });

    it('includes server URL in JSDoc on interface', () => {
      const doc = createDoc({
        servers: [
          {
            url: 'https://{environment}.api.example.com/{version}',
            variables: {
              environment: {
                default: 'production',
              } as ServerVariableObject,
              version: {
                default: 'v1',
              } as ServerVariableObject,
            },
          },
        ],
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('/** Server: https://{environment}.api.example.com/{version} */');
    });
  });

  describe('binary stream response types', () => {
    it('generates StreamResponse for application/octet-stream response', () => {
      const doc = createDoc({
        paths: {
          '/files/{id}': {
            get: {
              parameters: [
                { name: 'id', in: 'path' as const, required: true, schema: { type: 'string' } },
              ],
              responses: {
                '200': {
                  description: 'Binary file',
                  content: {
                    'application/octet-stream': {
                      schema: { type: 'string', format: 'binary' },
                    },
                  },
                },
              },
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('export type GetFilesIdResponse = StreamResponse;');
      expect(result).toContain('export class StreamResponse {');
    });

    it('generates StreamResponse for image/* response', () => {
      const doc = createDoc({
        paths: {
          '/images/{id}': {
            get: {
              parameters: [
                { name: 'id', in: 'path' as const, required: true, schema: { type: 'string' } },
              ],
              responses: {
                '200': {
                  description: 'Image',
                  content: {
                    'image/png': {
                      schema: { type: 'string', format: 'binary' },
                    },
                  },
                },
              },
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('export type GetImagesIdResponse = StreamResponse;');
    });

    it('generates string for JSON response (non-binary)', () => {
      const doc = createDoc({
        paths: {
          '/data': {
            get: {
              responses: {
                '200': {
                  description: 'JSON data',
                  content: {
                    'application/json': {
                      schema: { type: 'string' },
                    },
                  },
                },
              },
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('export type GetDataResponse = string;');
    });

    it('always emits StreamResponse class', () => {
      const doc = createDoc({
        paths: {
          '/items': {
            get: {
              responses: {
                '200': {
                  description: 'A list of items',
                  content: {
                    'application/json': {
                      schema: {
                        type: 'array',
                        items: { type: 'string' },
                      },
                    },
                  },
                },
              },
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));
      expect(result).toContain('export class StreamResponse {');
      expect(result).toContain('export function streamResponse(');
    });
  });

  describe('reserved name collision handling', () => {
    it('renames user schema that collides with ErrorResponse', () => {
      const doc = createDoc({
        components: {
          schemas: {
            ErrorResponse: {
              type: 'object',
              properties: {
                code: { type: 'integer' },
                message: { type: 'string' },
              },
              required: ['code', 'message'],
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));

      expect(result).toContain('export type ErrorResponseModel = {');
      expect(result).toContain(' code: number;');
      expect(result).toContain(' message: string;');
      expect(result).toContain('export class ErrorResponse');
      expect(result).not.toMatch(/export type ErrorResponse =/);
    });

    it('renames user schema that collides with ApiError', () => {
      const doc = createDoc({
        components: {
          schemas: {
            ApiError: {
              type: 'object',
              properties: {
                detail: { type: 'string' },
              },
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));

      expect(result).toContain('export type ApiErrorModel = {');
      expect(result).toContain('export class ApiError<TStatus extends number, TData>');
    });

    it('renames user schema that collides with StreamResponse', () => {
      const doc = createDoc({
        components: {
          schemas: {
            StreamResponse: { type: 'string' },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));

      expect(result).toContain('export type StreamResponseModel = string;');
      expect(result).toContain('export class StreamResponse {');
    });

    it('does not rename schemas without collisions', () => {
      const doc = createDoc({
        components: {
          schemas: {
            Product: {
              type: 'object',
              properties: { name: { type: 'string' } },
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));

      expect(result).toContain('export type Product = {');
      expect(result).not.toContain('ProductModel');
    });

    it('renames $ref references to collided schemas in response types', () => {
      const doc = createDoc({
        components: {
          schemas: {
            ErrorResponse: {
              type: 'object',
              properties: {
                message: { type: 'string' },
              },
            },
          },
        },
        paths: {
          '/items': {
            get: {
              responses: {
                '200': { description: 'OK' },
                '400': {
                  description: 'Bad Request',
                  content: {
                    'application/json': {
                      schema: { $ref: '#/components/schemas/ErrorResponse' },
                    },
                  },
                },
              },
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));

      expect(result).toContain('export type GetItemsError400 = ErrorResponseModel;');
      expect(result).toContain('export type GetItemsErrors = ApiError<400, GetItemsError400>;');
    });

    it('renames $ref references in allOf', () => {
      const doc = createDoc({
        components: {
          schemas: {
            ErrorResponse: {
              type: 'object',
              properties: { code: { type: 'integer' } },
            },
            DetailedError: {
              allOf: [
                { $ref: '#/components/schemas/ErrorResponse' },
                { type: 'object', properties: { detail: { type: 'string' } } },
              ],
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));

      expect(result).toContain('export type DetailedError = ErrorResponseModel &');
    });

    it('handles multiple reserved name collisions in one spec', () => {
      const doc = createDoc({
        components: {
          schemas: {
            ErrorResponse: {
              type: 'object',
              properties: { message: { type: 'string' } },
            },
            StreamResponse: { type: 'string' },
            ApiError: { type: 'string' },
            Product: {
              type: 'object',
              properties: { name: { type: 'string' } },
            },
          },
        },
      });
      const result = generateContracts(doc, makeResolver(doc));

      expect(result).toContain('export type ErrorResponseModel = {');
      expect(result).toContain('export type StreamResponseModel = string;');
      expect(result).toContain('export type ApiErrorModel = string;');
      expect(result).toContain('export type Product = {');
      expect(result).toContain('export class ErrorResponse');
      expect(result).toContain('export class StreamResponse {');
      expect(result).toContain('export class ApiError');
    });
  });
});
